name: Application CI
on:
  push:
    branches: [ "main", "stage", "test" ]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  call-central-pipeline:
    uses: App-of-apps-argo-example/pipeline-templates/.github/workflows/reusable-build-deploy.yaml@main
    with:
      app_name: "microservice-b"
      environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
    secrets:
      GITOPS_BOT_TOKEN: ${{ secrets.GITOPS_BOT_TOKEN }}
